Sc 4728 maple js add address constants to the repo
maple-labs/maple-js pull request #2
Opened 2022-02-10 23:07 UTC by xhad

## Description
This adds a local artifacts folder with addresses and a script that generates addresses for export from the main package. The addresses for all networks is exported from the sdk as an `addresses` object.

```javascript
import { addresses } from '@maplelabs/maple-js
```

2022-02-10 23:31 UTC, michaelsmueller commented on src/addresses/kovan-dev.ts
> +  DebtLockerV2Factory: '0x5b85BD12B7DF56Ad1aFB5D22799c91088A2Fa880',
Note that we have not included contracts such as `DebtLockerV2` and `LoanV2`

The webapp doesn't need these but the subgraph for example uses them. I think the subgraph should import the modules it needs directly (not from the SDK), so we're probably fine here, but just wanted to point this out

2022-02-10 23:36 UTC, michaelsmueller commented on src/addresses/rinkeby-dev.ts
> +  WETH: '0xbd7d6a9d4520E611113AaE5CddF3f1AC1ceCffD8',
Note in deploy, subgraph and webapp there has some confusion in naming between WETH vs. WETH9

This led to the withdrawal bug (where Apollo couldn't post collateral) so we should probably decide and standardize

2022-02-10 23:36 UTC, michaelsmueller commented on src/addresses/rinkeby-dev.ts
> +  USDC: '0x9784a33c3dC1Ba3bEB0C6aF7947203341710d965',
Do we wish to provide our deployed oracle addresses?

2022-02-11 00:07 UTC, xhad commented on src/addresses/kovan-dev.ts
> +  DebtLockerV2Factory: '0x5b85BD12B7DF56Ad1aFB5D22799c91088A2Fa880',
Where would you get the addresses for the Subgraph? My thinking is to move away from symlinking the artifacts folder everywhere and only use the an addresses constants file

2022-02-11 00:08 UTC, xhad commented on src/addresses/kovan-dev.ts
> +  DebtLockerV2Factory: '0x5b85BD12B7DF56Ad1aFB5D22799c91088A2Fa880',
DebtLockerV2 and LoanV2 are created from templates and do not have addresses, correct?

2022-02-11 00:09 UTC, xhad commented on src/addresses/rinkeby-dev.ts
> +  WETH: '0xbd7d6a9d4520E611113AaE5CddF3f1AC1ceCffD8',
yes, this WETH9 has been a real bother. I would say we go with WETH everywhere.

2022-02-11 00:09 UTC, xhad commented on src/addresses/rinkeby-dev.ts
> +  USDC: '0x9784a33c3dC1Ba3bEB0C6aF7947203341710d965',
yes, we want to include all addresses here. Which ones are missing?

2022-02-11 00:50 UTC, michaelsmueller commented on src/addresses/kovan-dev.ts
> +  DebtLockerV2Factory: '0x5b85BD12B7DF56Ad1aFB5D22799c91088A2Fa880',
Good point about the addresses. So the subgraph will need to pull that in from the SDK. So probably best for the subgraph to pull in the ABIs from the SDK too.

Totally agree about getting away from symlinking.

`DebtLockerV2` and `LoanV2` are the implementation contracts to which delegate calls are performed by the deployed proxies. Yes they are templates (for the LoanV2 and DebtLockerV2 proxies)

2022-02-11 01:16 UTC, xhad commented on src/addresses/kovan-dev.ts
> +  DebtLockerV2Factory: '0x5b85BD12B7DF56Ad1aFB5D22799c91088A2Fa880',
I think it will be helpful to have all of the ABIs in one place as well if traders or others want to interact with the protocol they only need to pull in the SDK, instead of the various other evm repos. I'll try to add the ABIs

2022-02-11 01:41 UTC, michaelsmueller commented on src/addresses/rinkeby-dev.ts
> +  USDC: '0x9784a33c3dC1Ba3bEB0C6aF7947203341710d965',
```ts
PriceOracleUSDC: '0x4D31De6e7b810328AF4196dC6D5b400C31B34180',
PriceOracleWBTC: '0xEb63E18E54912FB7437e7c974C0Cd03D8d830906',
```

The bundle also has `ChainLinkAggregatorWBTC` but I think we should have the SDK get the Chainlink price feed aggregator from the (Maple) Oracle contract since this may be updated (also Maple can supply an override price)

2022-02-11 01:58 UTC, michaelsmueller commented on src/addresses/mainnet.ts
> +  PremiumCalc: '0xe88Ab4Cf1Ec06840d16feD69c964aD9DAFf5c6c2',
`mainnet` bundle has
```ts
PriceOracleUSDC: '0x5DC5E14be1280E747cD036c089C96744EBF064E7',
PriceOracleWBTC: '0xF808ec05c1760DE4794813d08d2Bf1E16e7ECD0B',
```

I thought the protocol assumes a constant price oracle for USDC, so not sure why we have an oracle. Question for Lucas.

Following are additional oracles we have in the subgraph as indexed when the Governor called `setPriceOracle` on MapleGlobals.sol. Would propose these addresses be added as well:

```json
      {
        "id": "0x514910771af9ca656af840dff83e8264ecf986ca",
        "priceFeed": "0x5ad18e4ce9c88c3c266a1befe924cd6eaf812f24",
        "symbol": "LINK"
      },
      {
        "id": "0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9",
        "priceFeed": "0xcc903496edee42f1a298c63905c19a42af708b15",
        "symbol": "AAVE"
      },
      {
        "id": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
        "priceFeed": "0x40db4461402125fd848ccf89f39166d42db0aa47",
        "symbol": "WETH"
      },
```

2022-02-11 03:11 UTC, xhad commented on src/addresses/mainnet.ts
> +  PremiumCalc: '0xe88Ab4Cf1Ec06840d16feD69c964aD9DAFf5c6c2',
Seems like this is the same convo as above so I will close the one above and continue here

2022-05-12 10:58 UTC, Jakkc approved these changes

2022-05-12 16:39 UTC, michaelsmueller requested changes
nice! just the block heights and we're good

2022-05-12 16:39 UTC, michaelsmueller commented on artifacts/localhost/manifest.json
> +  "blockheight": 27670616,
this should be 0

2022-05-12 16:39 UTC, michaelsmueller commented on src/addresses/localhost.ts
> +    blockheight: 27670616,
here too 0

2022-05-12 17:08 UTC, michaelsmueller approved these changes

2022-05-12 17:10 UTC, merged